version: '3'

services:
  moodle:
    hostname: moodle
    container_name: moodle
    image: khalibre/moodle-base:dev
    environment:
      MOODLE_DB_HOST: 'moodle-db'
      MOODLE_DB_NAME: 'moodle'
      MOODLE_DB_USER: 'moodle'
      MOODLE_DB_PASSWORD: 'moodle'
      MOODLE_URL: 'http://localhost'
      MOODLE_ADMIN_USER: 'admin'
      MOODLE_ADMIN_PASSWORD: 'Admin123'
      MOODLE_ADMIN_EMAIL: 'admin@example.com'
      MOODLE_LANG: 'en'
      MOODLE_SITE_NAME: 'Moodle Test'
      MOODLE_SITE_FULLNAME: 'Moodle Test'
      SSL_PROXY: 'false'
      SMTP_HOSTS: 'maildev'
      SMTP_USER: ''
      SMTP_PASSWORD: ''
      SMTP_MAXBULK: ''
      NO_REPLY_ADDRESS: ''
      # CRON_BROWSER_PASS: 'Pass123'
      # MOODLE_MANAGER: '${MOODLE_MANAGER}'
      # MANAGER_PASSWORD: '${MANAGER_PASSWORD}'
      # INSTALL_TYPE: '${INSTALL_TYPE}'
      # SCHOOL_TYPE: '${SCHOOL_TYPE}'
    ports:
      - 80:80

  moodle-db:
    hostname: moodle-db
    container_name: moodle-db
    image: mariadb:10.3
    environment:
      MARIADB_ROOT_PASSWORD: 'moodle'
      MARIADB_DATABASE: 'moodle'
      MARIADB_USER: 'moodle'
      MARIADB_PASSWORD: 'moodle'
